INSERT INTO ADMIN_ROLE (
    ROLE_ID, ROLE_CODE, ROLE_NAME, ENABLED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    ADMIN_ROLE_SEQ.NEXTVAL, 'ADMIN', 'Administrator', 1, 'seed', SYSTIMESTAMP, 'seed', SYSTIMESTAMP
);

INSERT INTO ADMIN_ROLE (
    ROLE_ID, ROLE_CODE, ROLE_NAME, ENABLED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    ADMIN_ROLE_SEQ.NEXTVAL, 'MENU_MANAGER', 'Menu Manager', 1, 'seed', SYSTIMESTAMP, 'seed', SYSTIMESTAMP
);

INSERT INTO ADMIN_USER (
    USER_ID, LOGIN_ID, USER_NAME, ENABLED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    ADMIN_USER_SEQ.NEXTVAL, 'admin', 'Seed Admin', 1, 'seed', SYSTIMESTAMP, 'seed', SYSTIMESTAMP
);

INSERT INTO ADMIN_MENU (
    MENU_ID, MENU_CODE, MENU_NAME, PARENT_MENU_ID, SORT_ORDER, ENABLED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
) VALUES (
    ADMIN_MENU_SEQ.NEXTVAL, 'ADMIN_ROOT', 'Admin', NULL, 10, 1, 'seed', SYSTIMESTAMP, 'seed', SYSTIMESTAMP
);

INSERT INTO ADMIN_MENU (
    MENU_ID, MENU_CODE, MENU_NAME, PARENT_MENU_ID, SORT_ORDER, ENABLED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
)
SELECT ADMIN_MENU_SEQ.NEXTVAL, 'USER_LIST', 'User List', root.MENU_ID, 20, 1, 'seed', SYSTIMESTAMP, 'seed', SYSTIMESTAMP
  FROM ADMIN_MENU root
 WHERE root.MENU_CODE = 'ADMIN_ROOT';

INSERT INTO ADMIN_MENU (
    MENU_ID, MENU_CODE, MENU_NAME, PARENT_MENU_ID, SORT_ORDER, ENABLED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
)
SELECT ADMIN_MENU_SEQ.NEXTVAL, 'MENU_LIST', 'Menu List', root.MENU_ID, 30, 1, 'seed', SYSTIMESTAMP, 'seed', SYSTIMESTAMP
  FROM ADMIN_MENU root
 WHERE root.MENU_CODE = 'ADMIN_ROOT';

INSERT INTO ADMIN_USER_ROLE (USER_ID, ROLE_ID)
SELECT admin_user.USER_ID, admin_role.ROLE_ID
  FROM ADMIN_USER admin_user
  JOIN ADMIN_ROLE admin_role ON admin_role.ROLE_CODE = 'ADMIN'
 WHERE admin_user.LOGIN_ID = 'admin';

INSERT INTO ADMIN_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT admin_role.ROLE_ID, admin_menu.MENU_ID
  FROM ADMIN_ROLE admin_role
 CROSS JOIN ADMIN_MENU admin_menu
 WHERE admin_role.ROLE_CODE = 'ADMIN';

COMMIT;

