CREATE SEQUENCE ADMIN_USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN_ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN_MENU_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ADMIN_USER (
    USER_ID NUMBER(19) PRIMARY KEY,
    LOGIN_ID VARCHAR2(100) NOT NULL UNIQUE,
    USER_NAME VARCHAR2(100) NOT NULL,
    ENABLED NUMBER(1) NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE ADMIN_ROLE (
    ROLE_ID NUMBER(19) PRIMARY KEY,
    ROLE_CODE VARCHAR2(50) NOT NULL UNIQUE,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    ENABLED NUMBER(1) NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE ADMIN_MENU (
    MENU_ID NUMBER(19) PRIMARY KEY,
    MENU_CODE VARCHAR2(50) NOT NULL UNIQUE,
    MENU_NAME VARCHAR2(100) NOT NULL,
    PARENT_MENU_ID NUMBER(19),
    SORT_ORDER NUMBER(10) NOT NULL,
    ENABLED NUMBER(1) NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_ADMIN_MENU_PARENT FOREIGN KEY (PARENT_MENU_ID) REFERENCES ADMIN_MENU (MENU_ID)
);

CREATE TABLE ADMIN_USER_ROLE (
    USER_ID NUMBER(19) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_ADMIN_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_ADMIN_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES ADMIN_USER (USER_ID),
    CONSTRAINT FK_ADMIN_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ADMIN_ROLE (ROLE_ID)
);

CREATE TABLE ADMIN_ROLE_MENU (
    ROLE_ID NUMBER(19) NOT NULL,
    MENU_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_ADMIN_ROLE_MENU PRIMARY KEY (ROLE_ID, MENU_ID),
    CONSTRAINT FK_ADMIN_ROLE_MENU_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ADMIN_ROLE (ROLE_ID),
    CONSTRAINT FK_ADMIN_ROLE_MENU_MENU FOREIGN KEY (MENU_ID) REFERENCES ADMIN_MENU (MENU_ID)
);

